package View;

import Controller.DatTiecController;
import DAO.DatTiecDAO;
import DAO.DataBaseConnection;
import DAO.KhachHangDAO;
import DAO.ThongTinPhongDAO;
import Model.HoaDonTiec;
import Model.KhachHang;
import Model.ThongTinPhong;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author asus
 */
public class DatTiecJPane extends javax.swing.JPanel {
    DefaultTableModel tblHoaDonTiec, tblKhachHang;
    Date date = new Date();
    private ArrayList<KhachHang> listKhachHang;
    private ArrayList<HoaDonTiec> listHoaDonTiec;
    /**
     * Creates new form DatTiecJPane
     */
    public DatTiecJPane() {
        initComponents();
//        tblKhachHang = (DefaultTableModel) Table_KhachHang.getModel();
//        tblKhachHang.setColumnIdentifiers(new Object[]{"STT","Mã khách hàng", "Tên khách hàng", "Số điện thoại"});
//        showTable_KhachHang();
        resetButton();
        showMaPhong();
        tblHoaDonTiec = (DefaultTableModel) Table_HoaDonTiec.getModel();
        tblHoaDonTiec.setColumnIdentifiers(new Object[]{"Mã tiệc","Mã phòng", "Mã khách", "Ngày lập", "Ngày tổ chức", "Tình trạng", "Số khách", "Tiền cọc", "Tổng tiền", "Ghi chú"});
        showTable_HoaDonTiec();
    }
    
    public void resetButton(){
        Button_DatTiec.setEnabled(true);
        Button_Xoa.setEnabled(false);
        Button_Sua.setEnabled(false);
        Button_ChiTietTiec.setEnabled(false);
        Button_XuatHoaDon.setEnabled(false);
        Button_TimKiem.setEnabled(true);
    }
    public void showTable_KhachHang(){
        int i = 1;
        ArrayList<KhachHang> listKhachHang = new KhachHangDAO().getListKhachHang();
        for(KhachHang KH : listKhachHang){
            tblKhachHang.addRow(new Object[]{i++, KH.getMaKH(), KH.getTenKH(), KH.getSDT()});
        }
    }
    
    public void showTable_HoaDonTiec(){
        ArrayList<HoaDonTiec> listHDTiec = new DatTiecDAO().getListHDTiec();
        for(HoaDonTiec HDT : listHDTiec){
            tblHoaDonTiec.addRow(new Object[]{HDT.getMaTiec(), HDT.getMaPhong(), HDT.getMaKH(), new SimpleDateFormat("dd-MM-yyyy").format(HDT.getNgayLap()), new SimpleDateFormat("dd-MM-yyyy").format(HDT.getNgayToChuc()), HDT.getTinhTrang(), HDT.getSoKhach(), HDT.getTienCoc(), HDT.getTongTien(), HDT.getGhiChu()});
        }
    }
    
    public void updateTable_KhachHang(){
        tblKhachHang.setRowCount(0);
        showTable_KhachHang();
    }
    
    public void updateTable_HoaDonTiec(){
        tblHoaDonTiec.setRowCount(0);
        showTable_HoaDonTiec();
    }
    
    public void showMaPhong(){
        ArrayList<ThongTinPhong> ttMaPhg = new ThongTinPhongDAO().getListPhongDangSD();
        for(ThongTinPhong data : ttMaPhg){
            ComboBox_MaPhong.addItem(data.getMaPhg());
        }
        DateChooser_NgayToChuc.setMinSelectableDate(new java.util.Date());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Text_TenKhachHang = new javax.swing.JTextField();
        Text_SDT = new javax.swing.JTextField();
        Text_MaKhachHang = new javax.swing.JTextField();
        Button_ChonKhachHang = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Text_MaTiec = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ComboBox_MaPhong = new javax.swing.JComboBox<>();
        DateChooser_NgayToChuc = new com.toedter.calendar.JDateChooser();
        RadioButton_TinhTrang = new javax.swing.JRadioButton();
        Spinner_SoKhach = new javax.swing.JSpinner();
        Text_TienCoc = new javax.swing.JTextField();
        Text_TongTien = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Text_GhiChu = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        Button_XuatHoaDon = new javax.swing.JButton();
        Button_ChiTietTiec = new javax.swing.JButton();
        Button_DatTiec = new javax.swing.JButton();
        Button_TaoMoi = new javax.swing.JButton();
        Button_Sua = new javax.swing.JButton();
        Button_Xoa = new javax.swing.JButton();
        Button_TimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_HoaDonTiec = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1050, 746));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Thông tin người đặt");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mã khách hàng");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tên khách hàng");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Số điện thoại");

        Text_TenKhachHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_SDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_MaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Button_ChonKhachHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_ChonKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Search_Icon.png"))); // NOI18N
        Button_ChonKhachHang.setText("Chọn khách hàng");
        Button_ChonKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ChonKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text_MaKhachHang)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Button_ChonKhachHang)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Text_TenKhachHang)
                    .addComponent(Text_SDT))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Text_MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Text_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Text_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Button_ChonKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Thông tin tiệc");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Quản lí tiệc");

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mã tiệc");

        Text_MaTiec.setEditable(false);
        Text_MaTiec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Mã phòng");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Ngày tổ chức");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tình trạng");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Số khách");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Tiền cọc");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Tổng tiền");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Ghi chú");

        ComboBox_MaPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBox_MaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_MaPhongActionPerformed(evt);
            }
        });

        DateChooser_NgayToChuc.setDate(date);
        DateChooser_NgayToChuc.setDateFormatString("dd-MM-yyyy");
        DateChooser_NgayToChuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        RadioButton_TinhTrang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RadioButton_TinhTrang.setText("Đã thanh toán");

        Spinner_SoKhach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Spinner_SoKhach.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        Text_TienCoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_TongTien.setEditable(false);
        Text_TongTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_GhiChu.setColumns(20);
        Text_GhiChu.setRows(5);
        jScrollPane3.setViewportView(Text_GhiChu);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Text_TongTien))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioButton_TinhTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateChooser_NgayToChuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Spinner_SoKhach)
                            .addComponent(Text_TienCoc)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBox_MaPhong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Text_MaTiec)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Text_MaTiec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ComboBox_MaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(DateChooser_NgayToChuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(RadioButton_TinhTrang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(Spinner_SoKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text_TienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Text_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));

        Button_XuatHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_XuatHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Bill_Icon.png"))); // NOI18N
        Button_XuatHoaDon.setText("Xuất hóa đơn");
        Button_XuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_XuatHoaDonActionPerformed(evt);
            }
        });

        Button_ChiTietTiec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_ChiTietTiec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Party_Icon.png"))); // NOI18N
        Button_ChiTietTiec.setText("Chi tiết tiệc");
        Button_ChiTietTiec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ChiTietTiecActionPerformed(evt);
            }
        });

        Button_DatTiec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_DatTiec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/baseline_fact_check_black_24dp.png"))); // NOI18N
        Button_DatTiec.setText("Đặt tiệc");
        Button_DatTiec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DatTiecActionPerformed(evt);
            }
        });

        Button_TaoMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Button_TaoMoi.setText("Tạo mới");
        Button_TaoMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TaoMoiActionPerformed(evt);
            }
        });

        Button_Sua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Fix_Icon.png"))); // NOI18N
        Button_Sua.setText("Sửa");
        Button_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SuaActionPerformed(evt);
            }
        });

        Button_Xoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Delete_Icon.png"))); // NOI18N
        Button_Xoa.setText("Xóa");
        Button_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_XoaActionPerformed(evt);
            }
        });

        Button_TimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagine/Search_Icon.png"))); // NOI18N
        Button_TimKiem.setText("Tìm");
        Button_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Button_TaoMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_DatTiec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Sua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Xoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ChiTietTiec, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_XuatHoaDon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_TaoMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_DatTiec, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_XuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_ChiTietTiec, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Table_HoaDonTiec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tiệc", "Mã phòng", "Mã khách", "Ngày lập", "Ngày tổ chức", "Tình trạng", "Số khách", "Tiền cọc", "Tổng tiền", "Ghi chú"
            }
        ));
        Table_HoaDonTiec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_HoaDonTiecMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_HoaDonTiec);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public KhachHang getTTKhachHang(){
        ChonKhachHang ttKH = new ChonKhachHang();
        int result =    JOptionPane.showConfirmDialog(null, ttKH, "Chọn khách hàng", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION)
        {
            return ttKH.returnTTKH();
        }
        else return null;
    }
    
    private void Button_ChonKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ChonKhachHangActionPerformed
        ChonKhachHang ttKH = new ChonKhachHang();
        int result =    JOptionPane.showConfirmDialog(null, ttKH, "Chọn khách hàng", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION)
        {
            Text_MaKhachHang.setText(String.valueOf(ttKH.returnTTKH().getMaKH()));
            Text_TenKhachHang.setText(ttKH.returnTTKH().getTenKH());
            Text_SDT.setText(ttKH.returnTTKH().getSDT());
        }

    }//GEN-LAST:event_Button_ChonKhachHangActionPerformed

    private void Button_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TimKiemActionPerformed
        HoaDonTiec HDT = new HoaDonTiec();
        HDT.setTenKH(Text_TenKhachHang.getText());
        HDT.setMaPhong(ComboBox_MaPhong.getSelectedItem().toString());
        if (RadioButton_TinhTrang.isSelected()){
                HDT.setTinhTrang(1);
            } else HDT.setTinhTrang(0);
        showResultTimKiemHDT(HDT);
    }//GEN-LAST:event_Button_TimKiemActionPerformed

    private void Button_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_XoaActionPerformed
        HoaDonTiec HDT = new HoaDonTiec();
        HDT.setMaTiec(Integer.parseInt(Text_MaTiec.getText()));
        int ret = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa dữ liệu?", "Xóa dữ liệu", JOptionPane.YES_NO_OPTION);
        if(ret == JOptionPane.YES_OPTION){
            if (new DatTiecDAO().XoaHoaDonTiec(HDT)){
                JOptionPane.showMessageDialog(this, "Xóa thành công.");
                resetThongTinTiec();
                updateTable_HoaDonTiec();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại.");
            }
        }
    }//GEN-LAST:event_Button_XoaActionPerformed

    private void Button_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SuaActionPerformed
        if (new DatTiecDAO().ktraMaPhong_KH(ComboBox_MaPhong.getSelectedItem().toString(), Integer.parseInt(Text_MaKhachHang.getText())) == false){
            JOptionPane.showMessageDialog(this, "Phòng và khách hàng không trùng khớp.");
            return ;
        }
        if(new DatTiecController().KtraJTextDatTiec(Text_MaKhachHang, Text_TienCoc, DateChooser_NgayToChuc)){
            HoaDonTiec HDT = new HoaDonTiec();
            HDT.setMaNV(1);
            HDT.setMaKH(Integer.parseInt(Text_MaKhachHang.getText()));
            HDT.setMaPhong(ComboBox_MaPhong.getSelectedItem().toString());
            HDT.setNgayLap(new java.util.Date());
            HDT.setNgayToChuc(DateChooser_NgayToChuc.getDate() );
            HDT.setSoKhach(Integer.parseInt(Spinner_SoKhach.getValue().toString()));
            HDT.setTienCoc(Integer.parseInt(Text_TienCoc.getText()));
            HDT.setTongTien(0);
            HDT.setGhiChu(Text_GhiChu.getText());
            if (RadioButton_TinhTrang.isSelected()){
                HDT.setTinhTrang(1);
            } else HDT.setTinhTrang(0);
            HDT.setMaTiec(Integer.parseInt(Text_MaTiec.getText()));
            int ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa dữ liệu?", "Sửa dữ liệu", JOptionPane.YES_NO_OPTION);
            if(ret == JOptionPane.YES_OPTION){
                if (new DatTiecDAO().SuaHoaDonTiec(HDT)){
                    JOptionPane.showMessageDialog(this, "Sửa thành công.");
                    resetThongTinTiec();
                    updateTable_HoaDonTiec();
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa thất bại.");
                }
            }
        }
    }//GEN-LAST:event_Button_SuaActionPerformed

    private void Button_DatTiecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DatTiecActionPerformed
//        if (ktraMaPhong(ComboBox_MaPhong.getSelectedItem().toString()) == true){
//            JOptionPane.showMessageDialog(this, "Phòng hiện không được thuê.");
//            return ;
//        }
        if (new DatTiecDAO().ktraMaPhong_KH(ComboBox_MaPhong.getSelectedItem().toString(), Integer.parseInt(Text_MaKhachHang.getText())) == false){
            JOptionPane.showMessageDialog(this, "Phòng và khách hàng không trùng khớp.");
            return ;
        }
        if(new DatTiecController().KtraJTextDatTiec(Text_MaKhachHang, Text_TienCoc, DateChooser_NgayToChuc)){
            HoaDonTiec HDT = new HoaDonTiec();
            HDT.setMaNV(1);
            HDT.setMaKH(Integer.parseInt(Text_MaKhachHang.getText()));
            HDT.setMaPhong(ComboBox_MaPhong.getSelectedItem().toString());
            HDT.setNgayLap(new java.util.Date());
            HDT.setNgayToChuc(DateChooser_NgayToChuc.getDate() );
            HDT.setSoKhach(Integer.parseInt(Spinner_SoKhach.getValue().toString()));
            HDT.setTienCoc(Integer.parseInt(Text_TienCoc.getText()));
            HDT.setTongTien(0);
            HDT.setGhiChu(Text_GhiChu.getText());
            if (RadioButton_TinhTrang.isSelected()){
                HDT.setTinhTrang(1);
            } else HDT.setTinhTrang(0);
            if (new DatTiecDAO().ThemHoaDonTiec(HDT)){
                JOptionPane.showMessageDialog(this, "Thêm thành công.");
                resetThongTinTiec();
                updateTable_HoaDonTiec();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại.");
            }
        }
    }//GEN-LAST:event_Button_DatTiecActionPerformed
    
    private void Button_TaoMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TaoMoiActionPerformed
        resetThongTinTiec();
        resetButton();
        updateTable_HoaDonTiec();
    }//GEN-LAST:event_Button_TaoMoiActionPerformed

    private void Table_HoaDonTiecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_HoaDonTiecMouseClicked
        ListSelectionModel listTable_HDT = Table_HoaDonTiec.getSelectionModel();
        listTable_HDT.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        Button_DatTiec.setEnabled(false);
        Button_Xoa.setEnabled(true);
        Button_Sua.setEnabled(true);
        Button_ChiTietTiec.setEnabled(true);
        Button_XuatHoaDon.setEnabled(true);
        Button_TimKiem.setEnabled(true);
        int indexTB = Table_HoaDonTiec.getSelectedRow();
        if (indexTB < tblHoaDonTiec.getRowCount() && indexTB >= 0){
            Text_MaTiec.setText(tblHoaDonTiec.getValueAt(indexTB, 0).toString());
            ComboBox_MaPhong.setSelectedItem(tblHoaDonTiec.getValueAt(indexTB, 1));
            try {
                DateChooser_NgayToChuc.setDate(new SimpleDateFormat("dd-MM-yyyy").parse(tblHoaDonTiec.getValueAt(indexTB, 4).toString()));
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            RadioButton_TinhTrang.setSelected(Integer.parseInt(tblHoaDonTiec.getValueAt(indexTB, 5).toString()) == 1);
            Spinner_SoKhach.setValue(Integer.parseInt(tblHoaDonTiec.getValueAt(indexTB, 6).toString()));
            Text_TienCoc.setText(tblHoaDonTiec.getValueAt(indexTB, 7).toString());
            Text_TongTien.setText(tblHoaDonTiec.getValueAt(indexTB, 8).toString());
            if (tblHoaDonTiec.getValueAt(indexTB, 9) != null){
                Text_GhiChu.setText(tblHoaDonTiec.getValueAt(indexTB, 9).toString());
            }
            KhachHang KH = new DatTiecDAO().getKHByMaKH(Integer.parseInt(tblHoaDonTiec.getValueAt(indexTB, 2).toString()));
//            showResultTimKiem(KH);
            Text_MaKhachHang.setText(Integer.toString(KH.getMaKH()));
            Text_TenKhachHang.setText(KH.getTenKH());
            Text_SDT.setText(KH.getSDT());
        }
    }//GEN-LAST:event_Table_HoaDonTiecMouseClicked

    private void Button_ChiTietTiecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ChiTietTiecActionPerformed
        ChiTietTiecJrame ctt = new ChiTietTiecJrame(Integer.parseInt(Text_MaTiec.getText().toString()));
        ctt.setLocationRelativeTo(null);
        ctt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ctt.setVisible(true);
        ctt.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e){
                updateTable_HoaDonTiec();
            }
        });
    }//GEN-LAST:event_Button_ChiTietTiecActionPerformed

    private void ComboBox_MaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_MaPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_MaPhongActionPerformed

    private void Button_XuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_XuatHoaDonActionPerformed
        int matiec = Integer.parseInt(Text_MaTiec.getText().toString());
        HashMap para = new HashMap();
        para.put("matiec", matiec);
        viewReport("src\\Reports\\XuatHoaDonTiec.jasper", para);
    }//GEN-LAST:event_Button_XuatHoaDonActionPerformed
    
    public void resetThongTinTiec(){
        Text_MaTiec.setText("");
        ComboBox_MaPhong.setSelectedItem(1);
        DateChooser_NgayToChuc.setDate(null);
        RadioButton_TinhTrang.setSelected(false);
        Spinner_SoKhach.setValue(0);
        Text_TienCoc.setText("");
        Text_TongTien.setText("");
        Text_GhiChu.setText("");
    }
    public void clearTextKhachHang(){
        Text_MaKhachHang.setText("");
        Text_TenKhachHang.setText("");
        Text_SDT.setText("");
    }
    public void showResultTimKiem(KhachHang khachhangInput){
        listKhachHang = new DatTiecDAO().TimKiemKhachHang(khachhangInput);
        tblKhachHang.setRowCount(0);
        int i = 1;
        for(KhachHang kh : listKhachHang){
            tblKhachHang.addRow(new Object[]{i++, kh.getMaKH(), kh.getTenKH(), kh.getSDT()});
        }
        if(listKhachHang.size() <= 0)
            JOptionPane.showMessageDialog(this,"Không tìm thấy thông tin khách hàng. Vui lòng kiểm tra lại!");
    }
    
    public void showResultTimKiemHDT(HoaDonTiec HDTInput){
        listHoaDonTiec = new DatTiecDAO().TimKiemHDT(HDTInput);
        tblHoaDonTiec.setRowCount(0);
        for(HoaDonTiec HDT : listHoaDonTiec){
            tblHoaDonTiec.addRow(new Object[]{HDT.getMaTiec(), HDT.getMaPhong(), HDT.getMaKH(), new SimpleDateFormat("dd-MM-yyyy").format(HDT.getNgayLap()), new SimpleDateFormat("dd-MM-yyyy").format(HDT.getNgayToChuc()), HDT.getTinhTrang(),
                                              HDT.getSoKhach(), HDT.getTienCoc(), HDT.getTongTien(), HDT.getGhiChu()});
        }
        if(listHoaDonTiec.size() <= 0)
            JOptionPane.showMessageDialog(this,"Không tìm thấy thông tin khách hàng. Vui lòng kiểm tra lại!");
    }
    
    public boolean ktraMaPhong(String maphg){
        ArrayList<String> MaPhongDangSD = new DatTiecDAO().getListMaPhgDangSD();
        for (String data : MaPhongDangSD){
            if (data.equals(maphg)) return false;
        }
        return true;
    }
    
    public void viewReport(String fileName, HashMap para){
        try {
            JasperPrint jasperPrint = JasperFillManager.fillReport(fileName, para, DataBaseConnection.getConnection());
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_ChiTietTiec;
    private javax.swing.JButton Button_ChonKhachHang;
    private javax.swing.JButton Button_DatTiec;
    private javax.swing.JButton Button_Sua;
    private javax.swing.JButton Button_TaoMoi;
    private javax.swing.JButton Button_TimKiem;
    private javax.swing.JButton Button_Xoa;
    private javax.swing.JButton Button_XuatHoaDon;
    private javax.swing.JComboBox<String> ComboBox_MaPhong;
    private com.toedter.calendar.JDateChooser DateChooser_NgayToChuc;
    private javax.swing.JRadioButton RadioButton_TinhTrang;
    private javax.swing.JSpinner Spinner_SoKhach;
    private javax.swing.JTable Table_HoaDonTiec;
    private javax.swing.JTextArea Text_GhiChu;
    private javax.swing.JTextField Text_MaKhachHang;
    private javax.swing.JTextField Text_MaTiec;
    private javax.swing.JTextField Text_SDT;
    private javax.swing.JTextField Text_TenKhachHang;
    private javax.swing.JTextField Text_TienCoc;
    private javax.swing.JTextField Text_TongTien;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
